# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1220, 851)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.headingFrame = QtWidgets.QFrame(self.centralwidget)
        self.headingFrame.setGeometry(QtCore.QRect(0, 0, 1241, 61))
        self.headingFrame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.54, stop:0 rgba(204, 238, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.headingFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.headingFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.headingFrame.setObjectName("headingFrame")
        self.topicLabel = QtWidgets.QLabel(self.headingFrame)
        self.topicLabel.setGeometry(QtCore.QRect(389, 10, 431, 41))
        self.topicLabel.setStyleSheet("font: 70 25pt \"Candara\";")
        self.topicLabel.setObjectName("topicLabel")
        self.widgetsFrame = QtWidgets.QFrame(self.centralwidget)
        self.widgetsFrame.setGeometry(QtCore.QRect(0, 60, 1231, 61))
        self.widgetsFrame.setStyleSheet("border-top:2px solid rgb(216, 242, 255);\n"
"border-bottom:2px solid rgb(216, 242, 255);")
        self.widgetsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.widgetsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.widgetsFrame.setObjectName("widgetsFrame")
        self.selectGeojsonLineEdit = QtWidgets.QLineEdit(self.widgetsFrame)
        self.selectGeojsonLineEdit.setGeometry(QtCore.QRect(4, 14, 221, 30))
        self.selectGeojsonLineEdit.setStyleSheet("border: 1px solid rgb(0, 85, 255);")
        self.selectGeojsonLineEdit.setObjectName("selectGeojsonLineEdit")
        self.readGeojsonButton = QtWidgets.QPushButton(self.widgetsFrame)
        self.readGeojsonButton.setGeometry(QtCore.QRect(224, 14, 90, 30))
        self.readGeojsonButton.setStyleSheet("background-color: rgb(219, 243, 255);\n"
"border: 1px solid rgb(0, 85, 255);")
        self.readGeojsonButton.setObjectName("readGeojsonButton")
        self.readVidsLineEdit = QtWidgets.QLineEdit(self.widgetsFrame)
        self.readVidsLineEdit.setGeometry(QtCore.QRect(324, 14, 220, 30))
        self.readVidsLineEdit.setStyleSheet("border: 1px solid rgb(0, 85, 255);")
        self.readVidsLineEdit.setObjectName("readVidsLineEdit")
        self.readVidsButton = QtWidgets.QPushButton(self.widgetsFrame)
        self.readVidsButton.setGeometry(QtCore.QRect(543, 14, 90, 30))
        self.readVidsButton.setStyleSheet("background-color: rgb(219, 243, 255);\n"
"border: 1px solid rgb(0, 85, 255);")
        self.readVidsButton.setObjectName("readVidsButton")
        self.readMatchButton = QtWidgets.QPushButton(self.widgetsFrame)
        self.readMatchButton.setGeometry(QtCore.QRect(643, 14, 140, 30))
        self.readMatchButton.setStyleSheet("background-color: rgb(219, 243, 255);\n"
"border: 1px solid rgb(0, 85, 255);")
        self.readMatchButton.setObjectName("readMatchButton")
        self.lineEdit = QtWidgets.QLineEdit(self.widgetsFrame)
        self.lineEdit.setGeometry(QtCore.QRect(793, 14, 150, 30))
        self.lineEdit.setStyleSheet("border: 1px solid rgb(0, 85, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.calcGeomButton = QtWidgets.QPushButton(self.widgetsFrame)
        self.calcGeomButton.setGeometry(QtCore.QRect(953, 14, 93, 30))
        self.calcGeomButton.setStyleSheet("background-color: rgb(219, 243, 255);\n"
"border: 1px solid rgb(0, 85, 255);")
        self.calcGeomButton.setObjectName("calcGeomButton")
        self.splitFilesButton = QtWidgets.QPushButton(self.widgetsFrame)
        self.splitFilesButton.setGeometry(QtCore.QRect(1058, 9, 131, 38))
        self.splitFilesButton.setStyleSheet("background-color: rgb(219, 243, 255);\n"
"border: 1px solid rgb(0, 85, 255);")
        self.splitFilesButton.setObjectName("splitFilesButton")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(29, 120, 1161, 671))
        self.scrollArea.setStyleSheet("border: 1px solid rgb(216, 242, 255);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1159, 669))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1220, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.topicLabel.setText(_translate("MainWindow", "360 Videos To Pic Panos"))
        self.readGeojsonButton.setText(_translate("MainWindow", "Read Geojson"))
        self.readVidsButton.setText(_translate("MainWindow", "Read Videos"))
        self.readMatchButton.setText(_translate("MainWindow", "Read and Match Files"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Division Length(meters)"))
        self.calcGeomButton.setText(_translate("MainWindow", "Cal Geom"))
        self.splitFilesButton.setText(_translate("MainWindow", "Split Files"))
